# This is a real live access token associated with the
# test user `dash-test-user`.
# This token is generated by visiting
# https://plot.ly/o/authorize/?response_type=token&client_id=RcXzjux4DGfb8bWG9UNGpJUGsTaS0pUVHoEf7Ecl&redirect_uri=http://localhost:9595/oauth2/callback
# while logged in as that user and following the redirect
users = {
    'creator': {
        'username': 'dash-test-user',
        'oauth_token': 'SZO7wfzkQR43WjjqQpMDdtRnv2GsNN',
        'api_key': '9kCBELqYp54Dygjn7zhH',
        'pw': 'password'
    },
    'viewer': {
        'username': 'dash-test-viewer',
        'oauth_token': '8P1qbtfzMPJjqGGXPpnD4bN2f0wQvm',
        'pw': 'password'
    }
}
