# This is a real live access token associated with the
# test user `dash-test-user`.
# This token is generated by visiting
# https://plot.ly/o/authorize/?response_type=token&client_id=RcXzjux4DGfb8bWG9UNGpJUGsTaS0pUVHoEf7Ecl&redirect_uri=http://localhost:9595/oauth2/callback
# while logged in as that user and following the redirect
import os

users = {
    'creator': {
        'username': os.getenv('TEST_CREATOR_USERNAME'),
        'oauth_token': os.getenv('TEST_CREATOR_TOKEN'),
        'api_key': os.getenv('TEST_CREATOR_API_KEY'),
        'pw': os.getenv('TEST_CREATOR_PW')
    },
    'viewer': {
        'username': os.getenv('TEST_VIEWER_USERNAME'),
        'oauth_token': os.getenv('TEST_VIEWER_TOKEN'),
        'pw': os.getenv('TEST_VIEWER_PW'),
    }
}
